version: '3.9'

x-images: &node-image
  build:
    context: .
    args:
      - NODE_IMAGE=node:20.10.0-bullseye
  user: node
  working_dir: /application

services:
  tacnet:
    container_name: tacnet
    <<: *node-image
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/application:cached
    command: /bin/bash -c "npm install && npm run start:debug"
    tty: true

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    # env_file:
    #   - .env

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongo-data:
