version: '3.9'

x-images: &node-image
  build:
    context: .
    args:
      - NODE_IMAGE=node:20.10.0-bullseye
  user: node
  working_dir: /application

services:
  tacnet:
    container_name: tacnet
    <<: *node-image
    ports:
      - 3000:3000
    volumes:
      - .:/application:cached
    command: /bin/bash -c "npm install && npm run start:debug"
    tty: true

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
